### ISSUE TITLE
ebuild uses autotools with deprecated EAPI 6

### ISSUE THREAD

**Issue by gryf** [halcon74/halcon-overlay#1]
Several ebuilds have deprecated api:
- sys-fs/eudev-4.9999
- sys-fs/eudev-3.2.10-r1
- sys-fs/eudev-9999
- app-text/evince-3.34.2
- dev-libs/klibc-2.0.4-r3
- dev-libs/klibc-2.0.4-r4
- sys-apps/v86d-0.1.10-r1
- sys-apps/v86d-0.1.10-r2

**Comment by halcon74** [comment]
Hi gryf,

Thanks for your report,

Surprise for me that someone else besides me is using halcon-overlay :)

The matter is I have faced issues with github recently, so switched to gitlab [1], and there the ebuilds of almost all these packages with deprecated EAPI have been removed or updated (except klibc) in the last commit. I don't use removed ones anymore.

Do you need these packages or did you report the issue *as itself*? 

[1] - https://gitlab.com/halcon741/halcon-overlay

**Comment by halcon74** [comment]
...Updated klibc too :)

**Comment by halcon74** [comment]
...And added the warning about gitlab to README here.

**Comment by gryf** [comment]
well, It's was annoying flood of text from portage. I'm only using `sys-power/pm-utils` and it's deps (sys-apps/hwids, virtual/dev-manager and x11-libs/libpciaccess).

**Comment by gryf** [comment]
Switched to gitlab repo. Seems like it work fine.
